/// Flutter icons WeddingIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeddingIcons
///      fonts:
///       - asset: fonts/WeddingIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeddingIcons {
  WeddingIcons._();

  static const _kFontFam = 'WeddingIcons';
  static const String? _kFontPkg = null;

  static const IconData bride_and_groom = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bride = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groom = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData excel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colorlogo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullcolorlogo = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData altfullcolorlogo = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
